"""empty message

Revision ID: ef5a19bfbf9c
Revises: 
Create Date: 2021-02-15 17:34:39.546819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5a19bfbf9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_in_english', sa.String(), nullable=True),
    sa.Column('name_in_russian', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('trainer', sa.String(), nullable=True),
    sa.Column('radio_field_week', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('free', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about'),
    sa.UniqueConstraint('free'),
    sa.UniqueConstraint('goals'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('picture'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('rating')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('day_in_week', sa.String(), nullable=True),
    sa.Column('time_to_study', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('teachers')
    op.drop_table('proposoal')
    op.drop_table('goals')
    # ### end Alembic commands ###
